version: '3'

services:
  mysql:
    image: mysql:5.7.24
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "cactus_app"
    ports: ['3306:3306']

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      PMA_HOST: "mysql"
      PMA_PORT: "3306"
    ports: ['8080:80']
    links:
      - mysql

  backend:
    build:
      ./backend
    volumes:
      - ./backend:/app
    environment:
      ENV: "development"
      PORT: "3000"
      DB_HOST: "mysql"
      DB_NAME: "cactus_app"
      DB_USERNAME: "root"
      DB_PASSWORD: "secret"
      DB_FORCE_RESTART: "false"
    ports: ['3000:3000']
    links:
      - mysql
    depends_on:
      - mysql
  
  client:
    build:
      ./client
    volumes:
      - ./client:/app
    ports: ['5000:3000']
    environment:
      # URL of the service that is running a backend instance
      BACKEND_SERVICE_URL: "http://backend:3000/"
    links:
      - backend
    depends_on:
      - backend