version: '2.3'

services:
  cactus.mysql:
    container_name: cactus_mysql
    image: mysql:5.7.24
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "cactus_app"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 6s
      retries: 10
    ports: ['3306:3306']

  cactus.phpmyadmin:
    container_name: cactus_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      PMA_HOST: "cactus.mysql"
      PMA_PORT: "3306"
    ports: ['8080:80']
    links:
      - cactus.mysql

  cactus.backend.admin:
    container_name: cactus_backend_admin
    build:
      ./backend_admin
    volumes:
      - ./backend_admin:/code
    environment:
      ENV: "development"
      DJANGO_ADMIN_USER: admin
      DJANGO_ADMIN_PASSWORD: "pass1234"
      DEBUG: "True" # Or "False"
    healthcheck:
      # test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      test: ["CMD",  "curl", "-I", "--fail", "http://localhost:8000/admin"]
      timeout: 6s
      retries: 10
    ports: ['6500:8000']
    links:
      - cactus.mysql
    depends_on:
      cactus.mysql:
        condition: service_started
      cactus.mysql:
        condition: service_healthy

  cactus.backend:
    container_name: cactus_backend
    build:
      ./backend
    volumes:
      - ./backend:/app
    environment:
      ENV: "development"
      PORT: "3000"
      DB_HOST: "cactus.mysql"
      DB_NAME: "cactus_app"
      DB_USERNAME: "root"
      DB_PASSWORD: "secret"
      DB_FORCE_RESTART: "false"

      # URL of the service that is running a backend instance
      BACKEND_SERVICE_URL: "http://cactus.backend.admin:8000/"

    ports: ['3000:3000']
    links:
      - cactus.mysql
      - cactus.backend.admin
    depends_on:
      cactus.mysql:
        condition: service_started
      cactus.mysql:
        condition: service_healthy
      cactus.backend.admin:
        condition: service_started
      cactus.backend.admin:
        condition: service_healthy
  
  cactus.client:
    container_name: cactus_client
    build:
      ./client
    volumes:
      - ./client:/app
    ports: ['5000:3000']
    environment:
      # URL of the service that is running a backend instance
      BACKEND_SERVICE_URL: "http://cactus.backend:3000/"

      # URL of the local image cdn service
      IMG_CDN_SERVICE_URL: "http://cactus.img_cdn:80/"

      # URL of the local video cdn service
      VIDEO_CDN_SERVICE_URL: "http://cactus.video_cdn:80/live/"
    links:
      - cactus.backend
      - cactus.img_cdn
      - cactus.video_cdn
    depends_on:
      - cactus.backend
      - cactus.img_cdn
      - cactus.video_cdn
  
  cactus.img_cdn: # Local image CDN service
    container_name: cactus_img_cdn
    build:
      ./image-cdn
    volumes:
      - ./image-cdn/images:/var/www
    ports: ['8000:80']
  
  cactus.video_cdn: # Local video CDN service
    container_name: cactus_video_cdn
    build:
      ./video-cdn
    volumes:
      - ./video-cdn/videos/:/var/www/hls/live
    ports: ['9000:80', '1935:1935']