version: '2.3'

services:
  cactus.postgres:
    container_name: cactus_postgres
    image: postgres:9.6.15-alpine
    command: --shared_buffers=384MB --max_connections=3000
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "cactus_app"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports: ['5432:5432']

  cactus.pgadmin:
    container_name: cactus_pgadmin
    image: fenglc/pgadmin4:2.1-python2.7-alpine
    environment:
      DEFAULT_USER: "postgres"
      DEFAULT_PASSWORD: "secret"
    ports: ['5050:5050']
    links:
      - cactus.postgres

  cactus.backend.admin:
    container_name: cactus_backend_admin
    build:
      ./backend_admin
    volumes:
      - ./backend_admin:/code
    environment:
      ENV: "development"
      DJANGO_ADMIN_USER: admin
      DJANGO_ADMIN_PASSWORD: "pass1234"
      DEBUG: "True" # Or "False"
    healthcheck:
      # test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      test: ["CMD",  "curl", "-I", "--fail", "http://localhost:8000/admin"]
      timeout: 6s
      retries: 10
    ports: ['6500:8000']
    links:
      - cactus.postgres
    depends_on:
      cactus.postgres:
        condition: service_started
      cactus.postgres:
        condition: service_healthy

  cactus.backend:
    container_name: cactus_backend
    build:
      ./backend
    volumes:
      - ./backend:/app
    environment:
      ENV: "development"
      PORT: "3000"
      DB_HOST: "cactus.postgres"
      DB_NAME: "cactus_app"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "secret"
      DB_FORCE_RESTART: "false"
      
      # Name of this service
      SERVICE_NAME: "cactus_backend"

      # Logger service URL
      LOGGER_SERVICE_HOST: "http://cactus.logger:5341/"

      # URL of the service that is running a backend instance
      BACKEND_SERVICE_URL: "http://cactus.backend.admin:8000/"

    ports: ['3000:3000']
    links:
      - cactus.postgres
      - cactus.backend.admin
    depends_on:
      cactus.postgres:
        condition: service_started
      cactus.postgres:
        condition: service_healthy
      cactus.backend.admin:
        condition: service_started
      cactus.backend.admin:
        condition: service_healthy

  cactus.bff:
    container_name: cactus_bff
    build:
      ./bff
    volumes:
      - ./bff:/go/src/app
    links:
      - cactus.core
    depends_on:
      - cactus.core
    ports: ['4000:3000']
    environment:
      CACTUS_CORE_URL: "cactus.core:9040"

  cactus.core:
    container_name: cactus_core
    build:
      ./core
    volumes:
      - ./core:/go/src/app
    links:
      - cactus.core
    depends_on:
      - cactus.core
    ports: ['9040:9040']
    environment:
      DB_HOST: "cactus.postgres"
      DB_NAME: "cactus_app"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "secret"
    links:
      - cactus.postgres
    depends_on:
      cactus.postgres:
        condition: service_started
      cactus.postgres:
        condition: service_healthy
  
  cactus.client:
    container_name: cactus_client
    build:
      ./client
    volumes:
      - ./client:/app
    ports: ['5000:3000']
    environment:
      # Name of this service
      SERVICE_NAME: "cactus_client"

      # Logger service URL
      LOGGER_SERVICE_HOST: "http://cactus.logger:5341/"

      # URL of the service that is running a backend instance
      BACKEND_SERVICE_URL: "http://cactus.bff:3000/graphql"

      # URL of the local image cdn service
      IMG_CDN_SERVICE_URL: "http://cactus.img_cdn:80/"

      # URL of the local video cdn service
      VIDEO_CDN_SERVICE_URL: "http://cactus.video_cdn:80/live/"
    links:
      - cactus.bff
      - cactus.img_cdn
      - cactus.video_cdn
      - cactus.logger
    depends_on:
      - cactus.bff
      - cactus.img_cdn
      - cactus.video_cdn
      - cactus.logger
  
  cactus.img_cdn: # Local image CDN service
    container_name: cactus_img_cdn
    build:
      ./image-cdn
    volumes:
      - ./image-cdn/images:/var/www
    ports: ['8000:80']
  
  cactus.video_cdn: # Local video CDN service
    container_name: cactus_video_cdn
    build:
      ./video-cdn
    volumes:
      - ./video-cdn/videos/:/var/www/hls/live
    ports: ['9000:80', '1935:1935']
  
  cactus.logger: # Local video CDN service
    container_name: cactus_logger
    image: datalust/seq:5
    # volumes:
    #   - ./video-cdn/videos/:/var/www/hls/live
    environment:
      ACCEPT_EULA: "Y"
    ports: ['4040:80', '5341:5341']
