version: '2.3'

services:
  mysql:
    image: mysql:5.7.24
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "cactus_app"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports: ['3306:3306']

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      PMA_HOST: "mysql"
      PMA_PORT: "3306"
    ports: ['8080:80']
    links:
      - mysql

  backend_admin:
    build:
      ./backend_admin
    volumes:
      - ./backend_admin:/code
    environment:
      ENV: "development"
      DJANGO_ADMIN_USER: admin
      DJANGO_ADMIN_PASSWORD: "pass1234"
    healthcheck:
      # test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      test: ["CMD",  "curl", "-I", "--fail", "http://localhost:8000/admin"]
      timeout: 20s
      retries: 10
    ports: ['6500:8000']
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_started
      mysql:
        condition: service_healthy

  backend:
    build:
      ./backend
    volumes:
      - ./backend:/app
    environment:
      ENV: "development"
      PORT: "3000"
      DB_HOST: "mysql"
      DB_NAME: "cactus_app"
      DB_USERNAME: "root"
      DB_PASSWORD: "secret"
      DB_FORCE_RESTART: "false"
    ports: ['3000:3000']
    links:
      - mysql
      - backend_admin
    depends_on:
      mysql:
        condition: service_started
      mysql:
        condition: service_healthy
      backend_admin:
        condition: service_started
      backend_admin:
        condition: service_healthy
  
  client:
    build:
      ./client
    volumes:
      - ./client:/app
    ports: ['5000:3000']
    environment:
      # URL of the service that is running a backend instance
      BACKEND_SERVICE_URL: "http://backend:3000/"

      # URL of the local image cdn service
      IMG_CDN_SERVICE_URL: "http://img_cdn:3000/"

      # URL of the local video cdn service
      VIDEO_CDN_SERVICE_URL: "http://video_cdn:3000/"
    links:
      - backend
      - img_cdn
      - video_cdn
    depends_on:
      - backend
      - img_cdn
      - video_cdn
  
  img_cdn: # Local image CDN service
    build:
      ./image-cdn
    volumes:
      - ./image-cdn/src/img/:/app/src/img/
    ports: ['8000:3000']
  
  video_cdn: # Local video CDN service
    build:
      ./video-cdn
    volumes:
      - ./video-cdn/src/videos/:/app/src/videos/
    ports: ['9000:3000']